#pragma once


#define CAPS_LOCK_LED 		DRIVER_LED_TOTAL-5
#define NUM_LOCK_LED  		DRIVER_LED_TOTAL-4
#define SCROLL_LOCK_LED 	DRIVER_LED_TOTAL-3
#define COMPOSE_LED 		DRIVER_LED_TOTAL-2
#define KANA_LED			DRIVER_LED_TOTAL-1
